---
  # Versions
  irida_version: ""
  
  # Paths
  gvl_apps_home: "/mnt/gvl/apps"
  irida_home: "{{ gvl_apps_home }}/irida"
  irida_data: "{{ irida_home }}/data"
  irida_sequencing: "{{ irida_data }}/sequencing"
  irida_reference: "{{ irida_data }}/reference"
  irida_analysis: "{{ irida_data }}/analysis"
  irida_snapshot: "{{ irida_data }}/snapshot"
  
  irida_conf: "/etc/irida"
  irida_analytics: "{{ irida_conf }}/analytics"
  
  nginx_config: "/etc/nginx/sites-enabled"
  #tomcat_config: "/etc/tomcat7/conf"
  tomcat_config: "/var/lib/tomcat7/conf"
  tomcat_webapps: "/var/lib/tomcat7/webapps"
  
  #IRIDA URLS:
  irida_war_file: "https://github.com/phac-nml/irida/releases/download/0.11.3/irida.war"
  irida_conf_file: "https://raw.githubusercontent.com/phac-nml/irida/development/doc/administrator/web/config/irida.conf"
  irida_web_conf_file: "https://raw.githubusercontent.com/phac-nml/irida/development/doc/administrator/web/config/web.conf"

  # Database info
  database_user: ""
  database_prod: ""
  database_pass: ""

...
