---
  # Versions
  irida_version: ""
  
  # Paths
  gvl_apps_home: "/mnt/gvl/apps"
  irida_home: "{{ gvl_apps_home }}/irida"
  irida_data: "{{ irida_home }}/data"
  irida_sequencing: "{{ irida_data }}/sequencing"
  irida_reference: "{{ irida_data }}/reference"
  irida_analysis: "{{ irida_data }}/analysis"
  irida_snapshot: "{{ irida_data }}/snapshot"
  
  irida_conf: "/etc/irida"
  irida_analytics: "{{ irida_conf }}/analytics"
  
  nginx_config: "/etc/nginx/sites-enabled"
  #tomcat_config: "/etc/tomcat7/conf"
  tomcat_config: "/var/lib/tomcat7/conf"
  tomcat_webapps: "/var/lib/tomcat7/webapps"
  
  #IRIDA URLS:
  ##irida_war_file: "https://github.com/phac-nml/irida/releases/download/0.11.3/irida.war"
  irida_war_file: "http://irida.corefacility.ca/downloads/webapp/irida-fixgalaxyapi.war"
  irida_conf_file: "https://raw.githubusercontent.com/phac-nml/irida/development/doc/administrator/web/config/irida.conf"
  irida_web_conf_file: "https://raw.githubusercontent.com/phac-nml/irida/development/doc/administrator/web/config/web.conf"

  # Database info
  database_user: ""
  database_prod: ""
  database_pass: ""


  #tool installation variables

  galaxy_tools_galaxy_instance_url: 127.0.0.1/galaxy

  # A list of yml files that list the tools to be installed. See `files/tool_list.yaml.sample`
  galaxy_tools_tool_list_files: [ "tool_list.yaml" ]

  # should the playbook continue when errors are found
  galaxy_tools_ignore_errors: true

  # A system path from where this role will be run
  galaxy_tools_base_dir: /mnt/galaxy/tmp

  # Blank variable to make sure it's defined
  galaxy_tools_api_key: ''

  # A user for the Galaxy bootstrap user
  tools_admin_email: irida@local.localhost
  tools_admin_username: irida
  tools_admin_password: irida
  
  galaxy_server_dir: /mnt/galaxy/galaxy-app

  # A system path where a virtualend for Galaxy is installed
  galaxy_venv_dir: "{{ galaxy_server_dir }}/.venv"

  # A system path for Galaxy's main configuration file
  galaxy_config_file: "{{ galaxy_server_dir }}/config/galaxy.ini"

...
